### ISSUE TITLE
it fucking deleted everythin on my second phone 30gb worth of memories GONE

### ISSUE THREAD

**Issue by Poxiy** [droiter/openwrt-on-android#11]
FUCK YOU  I HATE YOU

**Comment by droiter** [comment]
Sorry about your loss. But that definitely not my fault.  If I want to do that, it is impossible to do it. If it's my fault, google won't let me enlist the app. I believe it is some bug of specific version of android. 

BTW, FUCK YOU TOO.

**Comment by Poxiy** [comment]
> Sorry about your loss. But that definitely not my fault. If I want to do that, it is impossible to do it. If it's my fault, google won't let me enlist the app. I believe it is some bug of specific version of android.
> 
> BTW, FUCK YOU TOO.

appereantly it was a bug of android 8.1 sorry for this yea
